.TH HTML_QUERY 1 2021-08-14 "" "Query html document"
.SH NAME
html_query \- html_query(html, queryName)
.SH SYNOPSIS
\fIhtml_query(html, queryName)\fR
.SH DESCRIPTION
.PP
Parse the given html document text and query of the html components as R object.
.PP
.SH OPTIONS
.PP
\fBhtml\fB \fR\- 
.PP
.PP
\fBqueryName\fB \fR\- 
.PP
.SH VALUE
.PP
a list/vector of html document element query result output
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.html_query at html.R:line 14
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2021
