.TH SEARCH 1 2021-08-14 "" "Do bing academic search"
.SH NAME
search \- search(term)
.SH SYNOPSIS
\fIsearch(term)\fR
.SH OPTIONS
.PP
\fBterm\fB \fR\- 
.PP
.SH VALUE
.PP
a list of term search result which is query from the bing academic search engine.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.search at search.R:line 9
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2021
