.\" man page create by R# package system.
.TH SEARCH 4 2020-06-02 "literature" "literature"
.SH NAME
literature \- Get profile of the details information about the given literature entry
.SH SYNOPSIS
\fIliterature(\fBliterature\fR as <generic> literatureEntry, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Get profile of the details information about the given literature entry
 
 the information of the details contains reference list, cites data, DOI, etc...
.PP
.SH OPTIONS
.PP
\fBliterature\fB \fR\- 
 the literature term entry from the @\fBM:academic.academic.search(System.String,System.Int32,SMRUCC.Rsharp.Runtime.Environment)\fR result.

.PP
.SH VALUE
.PP
the details information of the given article
.PP
.SH SEE ALSO
search
.SH FILES
.PP
academic.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright © xieguigang 2020
