.\" man page create by R# package system.
.TH SEARCH 4 2000-01-01 "profile.literature" "profile.literature"
.SH NAME
profile.literature \- Get profile of the given literature entry
.SH SYNOPSIS
\fIprofile.literature(\fBliterature\fR as <generic> literatureEntry);\fR
.SH DESCRIPTION
.PP
Get profile of the given literature entry
.PP
.SH OPTIONS
.PP
\fBliterature\fB \fR\- 
 the literature term entry from the @\fBM:academic.academic.search(System.String)\fR result.

.PP
.SH SEE ALSO
search
.SH FILES
.PP
academic.dll
.PP
.SH AUTHOR
Written by xie.guigang@gcmodeller.org
.SH COPYRIGHT
Copyright ©  2020
