.\" man page create by R# package system.
.TH SEARCH 4 2020-06-02 "search" "search"
.SH NAME
search \- Do bing academic term search
.SH SYNOPSIS
\fIsearch(\fBterm\fR as string, 
\fBoffset\fR as integer = 1, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Do bing academic term search
.PP
.SH OPTIONS
.PP
\fBterm\fB \fR\- the term string for search in bing.
.PP
.SH VALUE
.PP
a vector of the literature summary entry items.
.PP
.SH SEE ALSO
search
.SH FILES
.PP
academic.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright © xieguigang 2020
